# Generated by Django 6.0.3 on 2026-04-22 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('source', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='expense',
            name='user',
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(),
        ),
    ]
